#!/usr/bin/env python3
"""Read-only Phase65 source, development matrix and Phase66 boundary audit."""
from __future__ import annotations
import hashlib,json,sys
from collections import Counter
from pathlib import Path
from typing import Any
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE.parent));sys.path.insert(0,str(HERE))
from common import load_json,repo_root,require_clean_before_run,require_expected_head,utc_now,verify_pinned_inputs  # noqa:E402
from model import read_points  # noqa:E402
def canonical_sha(value:Any)->str:return hashlib.sha256(json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def validate_reserved_grid(contract:dict[str,Any])->dict[str,Any]:
 root=repo_root();reserved=load_json(root/contract["phase66_blind_boundary"]["reserved_grid"]);base={k:v for k,v in reserved.items() if k!="grid_sha256"};phase64=load_json(root/"experiment-results/phase64_pd_multiflow_graph_zero_shot/contracts/graph_payload_grid.json");layouts=load_json(root/"experiment-results/phase51_pd_l1_l3_physical_curve_library/contracts/model_transfer_layouts.json")["layouts"];layout_pages={row["model_id"]:{int(knot["page_count"]) for knot in row["knots"]} for row in layouts};reserved_pages={int(page) for values in reserved["configurations"].values() for vector in values for page in vector};development_pages={int(page) for value in phase64["configurations"].values() for vector in value["page_vectors"] for page in vector};expected_configs=contract["dataset_contract"]["configurations"];checks={"schema":reserved.get("schema_version")=="phase66-reserved-multiflow-blind-grid-v1","canonical_sha":reserved.get("grid_sha256")==canonical_sha(base),"targets_closed":reserved.get("phase66_targets_opened") is False and reserved.get("frozen_before_phase66_raw") is True,"models":reserved.get("models")==contract["dataset_contract"]["models"],"configurations":list(reserved.get("configurations",{}))==expected_configs,"ten_vectors_each":all(len(reserved["configurations"][config])==10 for config in expected_configs),"page_sets":reserved_pages==set(contract["phase66_blind_boundary"]["page_set"]) and development_pages==set(contract["phase66_blind_boundary"]["phase64_page_set"]),"zero_overlap":not (reserved_pages&development_pages),"pages_exist_for_models":all(reserved_pages<=layout_pages[model] for model in reserved["models"]),"new_placement_required":"no Phase64 endpoint tuple" in reserved.get("required_new_placement_policy","")}
 if not all(checks.values()):raise RuntimeError({"invalid_phase66_reserved_grid":checks})
 return {"status":"PASS","checks":checks,"grid_sha256":reserved["grid_sha256"],"development_pages":sorted(development_pages),"reserved_pages":sorted(reserved_pages),"reserved_vectors":sum(len(v) for v in reserved["configurations"].values()),"phase66_targets_read":False}
def run_checks(expected:str)->dict[str,Any]:
 head=require_expected_head(expected);require_clean_before_run();contract=load_json(HERE/"experiment.json");pins=verify_pinned_inputs(contract);root=repo_root();summary=load_json(root/"experiment-results/phase64_pd_multiflow_graph_zero_shot/summary.json")
 if summary.get("status") not in ("PASS","PASS_WITH_RUNTIME_VARIANCE","PASS_WITH_PLACEMENT_VARIANCE","PASS_WITH_RUNTIME_AND_PLACEMENT_VARIANCE") or summary.get("scientific_outcome")!="MULTIFLOW_GRAPH_ZERO_SHOT_FAIL_RETAIN_FOR_DEVELOPMENT" or summary.get("decision",{}).get("zero_shot_gate_pass") is not False:raise RuntimeError({"unexpected_phase64_summary":summary})
 rows=read_points(root/contract["dataset_contract"]["source"]);counts={"models":Counter(row["model_id"] for row in rows),"configurations":Counter(row["configuration"] for row in rows),"topologies":Counter(row["topology_level"] for row in rows),"vectors":Counter(row["vector_id"] for row in rows),"indices":Counter(int(row["vector_index"]) for row in rows)}
 def ordered(row:dict[str,Any])->bool:
  m=float(row["max_edge_baseline_us"]);b=float(row["busiest_endpoint_sum_us"]);s=float(row["sum_edge_baseline_us"]);tolerance=1e-12*max(1.0,abs(m),abs(b),abs(s));return b+tolerance>=m and s+tolerance>=b
 checks={"rows":len(rows)==240,"models":counts["models"]==Counter({model:120 for model in contract["dataset_contract"]["models"]}),"configurations":counts["configurations"]==Counter({config:60 for config in contract["dataset_contract"]["configurations"]}),"topologies":counts["topologies"]==Counter({level:80 for level in contract["dataset_contract"]["topology_levels"]}),"vector_cardinality":len(counts["vectors"])==80 and set(counts["vectors"].values())=={3},"ten_payload_folds":counts["indices"]==Counter({index:24 for index in range(10)}),"positive":all(float(row[field])>0 for row in rows for field in ("max_edge_baseline_us","graph_prediction_us","actual_concurrent_wave_us")),"graph_order":all(ordered(row) for row in rows)}
 if not all(checks.values()):raise RuntimeError({"phase65_development_matrix":checks,"counts":counts})
 reserved=validate_reserved_grid(contract);return {"schema_version":"phase65-preflight-v1","status":"PASS","workflow_commit":head,"captured_at_utc":utc_now(),"pinned_inputs":pins,"phase64":{"result_commit":contract["workflow_parent_result_commit"],"result_status":summary["status"],"scientific_outcome":summary["scientific_outcome"],"development_rows":len(rows),"labels_permitted_as_development":True},"phase66_reserved_grid":reserved,"checks":checks,"execution":{"gpu_used":False,"network_used":False,"new_physical_measurement":False,"phase66_targets_read":False}}
if __name__=="__main__":
 import argparse
 parser=argparse.ArgumentParser();parser.add_argument("--expected-workflow-commit",required=True);args=parser.parse_args();print(json.dumps(run_checks(args.expected_workflow_commit),ensure_ascii=False,indent=2,default=dict))
