#!/usr/bin/env python3
"""Select and freeze the simplest Phase65 graph correction on local CPU."""
from __future__ import annotations
import argparse,csv,json,sys,time
from pathlib import Path
from typing import Any
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE.parent));sys.path.insert(0,str(HERE))
from common import environment_record,load_json,refresh_manifest,repo_root,utc_now,validate_result_tree,write_json  # noqa:E402
from model import BASELINES,CANDIDATES,baseline_value,candidate_metric_rows,evaluate_candidates,fit_model,predict,prediction_rows,read_points,slice_metrics  # noqa:E402
from preflight import run_checks  # noqa:E402
def write_csv(path:Path,rows:list[dict[str,Any]])->None:
 if not rows:raise RuntimeError(f"empty Phase65 CSV: {path}")
 path.parent.mkdir(parents=True,exist_ok=True);fields=list(dict.fromkeys(key for row in rows for key in row))
 with path.open("w",encoding="utf-8",newline="") as stream:writer=csv.DictWriter(stream,fieldnames=fields,lineterminator="\n");writer.writeheader();writer.writerows(rows)
def run(expected:str,output:Path)->dict[str,Any]:
 started=time.monotonic();preflight=run_checks(expected)
 if output.exists():raise RuntimeError(f"refuse overwrite: {output}")
 contract=load_json(HERE/"experiment.json");rows=read_points(repo_root()/contract["dataset_contract"]["source"]);evaluation=evaluate_candidates(rows,contract);selected=evaluation["selected"];status="PASS" if selected is not None else "PASS_TARGET_NOT_MET";metrics=candidate_metric_rows(evaluation);selected_id=None if selected is None else selected["candidate_id"];model_bundle=None
 refit_predictions=[]
 for baseline in BASELINES:refit_predictions.extend(prediction_rows(rows,baseline,[baseline_value(baseline,row) for row in rows],"refit","all_development"))
 if selected is not None:
  specification=next(value for value in CANDIDATES if value["candidate_id"]==selected_id);model_bundle=fit_model(rows,specification);model_bundle.update({"workflow_commit":preflight["workflow_commit"],"source_result_commit":contract["workflow_parent_result_commit"],"inference_formula":"max(1.0, intercept + beta_M*M + beta_busy*(B-M) + beta_nonbusy*(S-B))","selection_evidence":{"payload_oof_folds":evaluation["payload_folds"],"topology_oof_folds":evaluation["topology_folds"],"payload_gate":selected["schemes"]["payload"]["gate"],"topology_gate":selected["schemes"]["topology"]["gate"],"simplest_passing_candidate":True,"refit_metrics_used_for_selection":False},"blind_status":{"phase66_reserved_grid_sha256":preflight["phase66_reserved_grid"]["grid_sha256"],"phase66_features_used_for_fit":False,"phase66_measurements_or_targets_used":False,"fresh_blind_validated":False}});refit_predictions.extend(prediction_rows(rows,selected_id,[predict(model_bundle,row) for row in rows],"refit","all_development"))
 refit_slices=[]
 for candidate_id in [*BASELINES,*([selected_id] if selected_id else [])]:refit_slices.extend(slice_metrics([row for row in refit_predictions if row["candidate_id"]==candidate_id],candidate_id,"refit"))
 payload_predictions=[row for row in evaluation["all_oof_predictions"] if row["oof_scheme"]=="payload"];topology_predictions=[row for row in evaluation["all_oof_predictions"] if row["oof_scheme"]=="topology"];payload_slices=[row for row in evaluation["all_oof_slices"] if row["oof_scheme"]=="payload"];topology_slices=[row for row in evaluation["all_oof_slices"] if row["oof_scheme"]=="topology"]
 output.mkdir(parents=True);write_json(output/"contracts/experiment.json",contract);write_json(output/"contracts/phase66_reserved_blind_grid.json",load_json(HERE/"phase66_reserved_blind_grid.json"));write_json(output/"audit/preflight.json",preflight);write_json(output/"audit/input_freeze.json",{"schema_version":"phase65-input-freeze-v1","workflow_commit":preflight["workflow_commit"],"source_result_commit":contract["workflow_parent_result_commit"],"pinned_inputs":preflight["pinned_inputs"],"development_rows":240,"phase64_labels_used_as_development":True,"phase66_reserved_grid_sha256":preflight["phase66_reserved_grid"]["grid_sha256"],"phase66_reserved_features_used_for_fit":False,"phase66_measurements_or_targets_read":False,"selection_uses_oof_only":True,"refit_metrics_used_for_selection":False})
 write_csv(output/"analysis/candidate_metrics.csv",metrics);write_csv(output/"analysis/payload_oof_predictions.csv",payload_predictions);write_csv(output/"analysis/payload_oof_slice_metrics.csv",payload_slices);write_csv(output/"analysis/topology_oof_predictions.csv",topology_predictions);write_csv(output/"analysis/topology_oof_slice_metrics.csv",topology_slices);write_csv(output/"analysis/refit_predictions.csv",refit_predictions);write_csv(output/"analysis/refit_slice_metrics.csv",refit_slices)
 if model_bundle is None:write_json(output/"model/multiflow_graph_correction.json",{"schema_version":"phase65-multiflow-graph-correction-v1","status":"NOT_FROZEN","reason":"no candidate passed both fixed OOF gates","workflow_commit":preflight["workflow_commit"]})
 else:write_json(output/"model/multiflow_graph_correction.json",model_bundle)
 baseline_rows={row["candidate_id"]:row for row in metrics if row["candidate_id"] in BASELINES};selected_row=None if selected_id is None else next(row for row in metrics if row["candidate_id"]==selected_id);elapsed=time.monotonic()-started;summary={"schema_version":"phase65-pd-graph-correction-development-result-v1","status":status,"workflow_commit":preflight["workflow_commit"],"source_result_commit":contract["workflow_parent_result_commit"],"completed_at_utc":utc_now(),"runtime_seconds":elapsed,"counts":{"development_points":240,"models":2,"configurations":4,"topologies":3,"payload_oof_folds":10,"topology_oof_folds":3,"fit_candidates":len(CANDIDATES),"gpu_measurements":0,"phase66_targets_used":0},"baselines":{"max_edge":baseline_rows["max_edge"],"r61_graph_extension":baseline_rows["r61_graph_extension"]},"selection":{"selected_candidate_id":selected_id,"selected_complexity_rank":None if selected is None else selected["complexity_rank"],"simplest_passing_candidate":selected is not None,"payload_oof":None if selected_row is None else {key:value for key,value in selected_row.items() if key.startswith("payload_")},"topology_oof":None if selected_row is None else {key:value for key,value in selected_row.items() if key.startswith("topology_")}},"formula":None if model_bundle is None else model_bundle["inference_formula"],"training_performed":True,"gpu_used":False,"network_used":False,"new_physical_measurement":False,"phase66_reserved_features_used_for_fit":False,"phase66_targets_opened":False,"fresh_blind_validated":False,"next_phase_permitted":status=="PASS","proved":"development OOF selection and full-development freeze of a lightweight correction for the four measured graph configurations","not_proved":"Phase66 fresh-blind accuracy, unseen-model/configuration generalization, larger graphs, end-to-end latency, compute, memory, queueing or scheduling"};write_json(output/"summary.json",summary)
 selected_text=selected_id or "none";payload_text="n/a" if selected_row is None else f"{100*float(selected_row['payload_overall_wape']):.3f}%";topology_text="n/a" if selected_row is None else f"{100*float(selected_row['topology_overall_wape']):.3f}%";(output/"README.md").write_text(f"# Phase65：PD多流通信图修正开发\n\n状态：{status}。按固定复杂度顺序选择的候选为 `{selected_text}`；payload OOF WAPE={payload_text}，topology OOF WAPE={topology_text}。本阶段只使用R64的240个development点，在本地CPU执行；未使用GPU、网络、新物理测量或任何Phase66 target。Phase66仍需fresh-blind。\n",encoding="utf-8");(output/"audit/environment.json").parent.mkdir(exist_ok=True);write_json(output/"audit/environment.json",environment_record());(output/"logs").mkdir();(output/"logs/runtime.log").write_text(f"completed={utc_now()} workflow_commit={preflight['workflow_commit']}\nstatus={status} selected={selected_text} runtime_seconds={elapsed:.6f}\npayload_oof_wape={None if selected_row is None else selected_row['payload_overall_wape']} topology_oof_wape={None if selected_row is None else selected_row['topology_overall_wape']}\ngpu=false network=false new_measurement=false phase66_target=false\n",encoding="utf-8");(output/"DONE").write_text(status+"\n",encoding="utf-8");refresh_manifest(output);tree=validate_result_tree(output)
 if not tree["ok"]:raise RuntimeError(tree)
 return summary
def main()->None:
 parser=argparse.ArgumentParser();parser.add_argument("--expected-workflow-commit",required=True);parser.add_argument("--output-dir",type=Path,default=repo_root()/"experiment-results/phase65_pd_graph_correction_development");args=parser.parse_args();print(json.dumps(run(args.expected_workflow_commit,args.output_dir.resolve()),ensure_ascii=False,indent=2))
if __name__=="__main__":main()
