#!/usr/bin/env python3
"""Independent compact-result verifier for Phase65."""
from __future__ import annotations
import argparse,csv,json,math,sys
from pathlib import Path
from typing import Any
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE.parent));sys.path.insert(0,str(HERE))
from common import load_json,repo_root,verify_result_manifest  # noqa:E402
from model import BASELINES,CANDIDATES,candidate_metric_rows,evaluate_candidates,fit_model,predict,read_points  # noqa:E402
from preflight import validate_reserved_grid  # noqa:E402
def read_csv(path:Path)->list[dict[str,str]]:
 with path.open(encoding="utf-8",newline="") as stream:return list(csv.DictReader(stream))
def truth(value:str)->bool:return value.lower()=="true"
def value_equal(actual:str,expected:Any)->bool:
 if isinstance(expected,bool):return truth(actual)==expected
 if isinstance(expected,(int,float)):return math.isclose(float(actual),float(expected),rel_tol=1e-12,abs_tol=1e-10)
 if expected is None:return actual==""
 return actual==str(expected)
def rows_reproduce(actual:list[dict[str,str]],expected:list[dict[str,Any]])->bool:
 return len(actual)==len(expected) and all(all(key in left and value_equal(left[key],value) for key,value in right.items()) for left,right in zip(actual,expected))
def verify(output:Path)->dict[str,Any]:
 expected_tree=load_json(HERE/"expected_outputs.json");files={str(path.relative_to(output)) for path in output.rglob("*") if path.is_file()};manifest=verify_result_manifest(output);contract=load_json(HERE/"experiment.json");result_contract=load_json(output/"contracts/experiment.json");summary=load_json(output/"summary.json");model=load_json(output/"model/multiflow_graph_correction.json");preflight=load_json(output/"audit/preflight.json");freeze=load_json(output/"audit/input_freeze.json");reserved_result=load_json(output/"contracts/phase66_reserved_blind_grid.json");reserved_source=load_json(HERE/"phase66_reserved_blind_grid.json");rows=read_points(repo_root()/contract["dataset_contract"]["source"]);evaluation=evaluate_candidates(rows,contract);expected_metrics=candidate_metric_rows(evaluation);candidate_metrics=read_csv(output/"analysis/candidate_metrics.csv");payload_predictions=read_csv(output/"analysis/payload_oof_predictions.csv");payload_slices=read_csv(output/"analysis/payload_oof_slice_metrics.csv");topology_predictions=read_csv(output/"analysis/topology_oof_predictions.csv");topology_slices=read_csv(output/"analysis/topology_oof_slice_metrics.csv");refit_predictions=read_csv(output/"analysis/refit_predictions.csv");refit_slices=read_csv(output/"analysis/refit_slice_metrics.csv");expected_payload=[row for row in evaluation["all_oof_predictions"] if row["oof_scheme"]=="payload"];expected_payload_slices=[row for row in evaluation["all_oof_slices"] if row["oof_scheme"]=="payload"];expected_topology=[row for row in evaluation["all_oof_predictions"] if row["oof_scheme"]=="topology"];expected_topology_slices=[row for row in evaluation["all_oof_slices"] if row["oof_scheme"]=="topology"];selected=evaluation["selected"];selected_id=None if selected is None else selected["candidate_id"];status="PASS" if selected is not None else "PASS_TARGET_NOT_MET";selected_rows=[row for row in candidate_metrics if truth(row["selected"])];first_passing=next((row for row in expected_metrics if row.get("target_guard") is True),None);selected_spec=None if selected is None else next(value for value in CANDIDATES if value["candidate_id"]==selected_id);expected_model=None if selected_spec is None else fit_model(rows,selected_spec);recorded={row["vector_id"]+"|"+row["topology_level"]:float(row["predicted_concurrent_wave_us"]) for row in refit_predictions if row["candidate_id"]==selected_id};recomputed={} if selected is None else {row["vector_id"]+"|"+row["topology_level"]:predict(model,row) for row in rows};reserved_audit=validate_reserved_grid(contract)
 checks={"manifest":manifest["ok"],"required_exact":files==set(expected_tree["required"]),"contract_exact":result_contract==contract,"status":summary.get("status")==status and status in contract["accepted_result_statuses"] and (output/"DONE").read_text().strip()==status,"source":summary.get("source_result_commit")==contract["workflow_parent_result_commit"] and freeze.get("source_result_commit")==contract["workflow_parent_result_commit"],"preflight":preflight.get("status")=="PASS" and preflight.get("workflow_commit")==summary.get("workflow_commit") and all(preflight.get("checks",{}).values()) and preflight.get("execution",{}).get("phase66_targets_read") is False,"reserved_grid":reserved_result==reserved_source and reserved_audit["status"]=="PASS" and freeze.get("phase66_reserved_grid_sha256")==reserved_source["grid_sha256"],"candidate_metrics_reproduced":rows_reproduce(candidate_metrics,expected_metrics),"payload_oof_reproduced":rows_reproduce(payload_predictions,expected_payload) and rows_reproduce(payload_slices,expected_payload_slices),"topology_oof_reproduced":rows_reproduce(topology_predictions,expected_topology) and rows_reproduce(topology_slices,expected_topology_slices),"cardinality":len(candidate_metrics)==7 and len(payload_predictions)==1680 and len(topology_predictions)==1680 and len(payload_slices)==210 and len(topology_slices)==210 and len(refit_predictions)==(720 if status=="PASS" else 480) and len(refit_slices)==(90 if status=="PASS" else 60),"fold_isolation":all(row["candidate_id"] in BASELINES or int(row["fold"])==int(row["vector_index"]) for row in payload_predictions) and all(row["candidate_id"] in BASELINES or row["fold"]==row["topology_level"] for row in topology_predictions),"selection":((len(selected_rows)==1 and selected_rows[0]["candidate_id"]==selected_id and first_passing is not None and first_passing["candidate_id"]==selected_id) if status=="PASS" else len(selected_rows)==0 and first_passing is None),"model_identity":status!="PASS" or (model.get("candidate_id")==selected_id and model.get("groups")==expected_model["groups"] and model.get("required_runtime_inputs")==expected_model["required_runtime_inputs"] and model.get("selection_evidence",{}).get("simplest_passing_candidate") is True and model.get("blind_status",{}).get("fresh_blind_validated") is False),"refit_reproducible":status!="PASS" or (recorded.keys()==recomputed.keys() and all(math.isclose(recorded[key],recomputed[key],rel_tol=1e-12,abs_tol=1e-9) for key in recorded)),"scope":summary.get("gpu_used") is False and summary.get("network_used") is False and summary.get("new_physical_measurement") is False and summary.get("phase66_targets_opened") is False and summary.get("fresh_blind_validated") is False and summary.get("counts",{}).get("gpu_measurements")==0 and summary.get("counts",{}).get("phase66_targets_used")==0 and freeze.get("refit_metrics_used_for_selection") is False}
 if not all(checks.values()):raise RuntimeError({"phase65_checks":checks,"selected_id":selected_id,"manifest":manifest})
 selected_metric=None if selected_id is None else next(row for row in candidate_metrics if row["candidate_id"]==selected_id);return {"status":"PASS","checks":checks,"workflow_commit":summary["workflow_commit"],"result_status":status,"selected_candidate_id":selected_id,"payload_oof_wape":None if selected_metric is None else float(selected_metric["payload_overall_wape"]),"topology_oof_wape":None if selected_metric is None else float(selected_metric["topology_overall_wape"]),"next_phase_permitted":summary["next_phase_permitted"],"manifest_files":manifest["manifest"]["checked_files"]}
def main()->None:
 parser=argparse.ArgumentParser();parser.add_argument("--output-dir",type=Path,default=repo_root()/"experiment-results/phase65_pd_graph_correction_development");args=parser.parse_args();print(json.dumps(verify(args.output_dir.resolve()),ensure_ascii=False,indent=2))
if __name__=="__main__":main()
