#!/usr/bin/env python3
"""Run deterministic Phase52 physical-cost and communication-only placement analysis."""
from __future__ import annotations
import argparse,json,math,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE.parent));sys.path.insert(0,str(HERE))
from common import environment_record,load_json,refresh_manifest,repo_root,utc_now,validate_result_tree,write_json  # noqa:E402
from analysis import aggregate_cost,aggregate_placement,compare_cost,compare_placement,cost_rows,placement,read_csv,write_csv  # noqa:E402
from preflight import run_checks  # noqa:E402

def run(expected:str,output:Path)->dict:
    preflight=run_checks(expected);spec=load_json(HERE/"experiment.json");paths={row["name"]:repo_root()/row["path"] for row in spec["pinned_inputs"]};predictions=read_csv(paths["phase49_frozen_predictions"]);targets=read_csv(paths["phase50_hfull_targets"]);curves=load_json(paths["phase51_curves"])["curves"]
    if output.exists():raise RuntimeError(f"refuse overwrite: {output}")
    costs,interpolation=cost_rows(predictions,targets,curves);cost_metrics=aggregate_cost(costs);cost_comparison=compare_cost(cost_metrics);rankings,decisions=placement(costs);placement_metrics=aggregate_placement(decisions);placement_comparison=compare_placement(placement_metrics);expected_counts=spec["expected_counts"]
    counts={"prediction_rows":len(predictions),"target_rows":len(targets),"unit_topology_cost_rows":len(costs),"placement_ranking_rows":len(rankings),"placement_decision_rows":len(decisions),"cost_metric_rows":len(cost_metrics),"cost_comparison_rows":len(cost_comparison),"placement_metric_rows":len(placement_metrics),"placement_comparison_rows":len(placement_comparison)}
    checks={"counts_exact":counts==expected_counts,"finite_nonnegative_costs":all(math.isfinite(float(r[name])) and float(r[name])>=0 for r in costs for name in ("predicted_cost_us_per_1000","teacher_cost_us_per_1000","predicted_cost_lower_us_per_1000","teacher_cost_lower_us_per_1000")),"fixed_candidates":all(r["ranking_scope"]=="communication_only_fixed_p1_d1_configuration" for r in decisions),"methods_exact":{r["method"] for r in costs}=={"h0","h0_plus_dnn_residual"},"levels_exact":{r["topology_level"] for r in costs}=={"L1","L2","L3"},"teacher_cost_method_invariant":_teacher_invariant(costs)}
    if not all(checks.values()):raise RuntimeError({"phase52_checks":checks,"counts":counts})
    overall_cost=[r for r in cost_comparison if r["slice_type"]=="overall"];overall_placement={r["method"]:r for r in placement_metrics if r["slice_type"]=="overall"};overall_pc=next(r for r in placement_comparison if r["slice_type"]=="overall")
    hypotheses={"cost_strict_mape_and_wape_all_topologies":len(overall_cost)==3 and all(r["strict_mape_and_wape_improvement"] for r in overall_cost),"placement_agreement_weakly_improved":overall_pc["agreement_weakly_improved"],"placement_mean_regret_weakly_improved":overall_pc["mean_regret_weakly_improved"]}
    roles=interpolation["roles"];clamps={"low_clamped_bins":sum(v.get("low_clamped_bins",0) for v in roles.values()),"high_clamped_bins":sum(v.get("high_clamped_bins",0) for v in roles.values()),"low_clamped_calls":sum(v.get("low_clamped_calls",0) for v in roles.values()),"high_clamped_calls":sum(v.get("high_clamped_calls",0) for v in roles.values())}
    sensitivity=_sensitivity(curves,placement_metrics,decisions,clamps,load_json(paths["phase51_quality"]))
    output.mkdir(parents=True);write_json(output/"contracts/experiment.json",spec);write_json(output/"audit/input_freeze.json",preflight);write_json(output/"audit/interpolation.json",interpolation);write_json(output/"audit/sensitivity.json",sensitivity);write_json(output/"audit/environment.json",{**environment_record(),"gpu_used":False,"network_used":False,"training_used":False,"checkpoint_loaded":False,"prediction_recomputed":False,"teacher_recomputed":False,"physical_measurement_performed":False});write_csv(output/"analysis/unit_topology_costs.csv.gz",costs);write_csv(output/"analysis/cost_metrics.csv",cost_metrics);write_csv(output/"analysis/cost_method_comparison.csv",cost_comparison);write_csv(output/"analysis/placement_rankings.csv.gz",rankings);write_csv(output/"analysis/placement_decisions.csv.gz",decisions);write_csv(output/"analysis/placement_metrics.csv",placement_metrics);write_csv(output/"analysis/placement_method_comparison.csv",placement_comparison)
    summary={"schema_version":"phase52-pd-physical-cost-placement-result-v1","status":"PASS","workflow_commit":expected,"completed_at_utc":utc_now(),"counts":counts,"checks":checks,"hypotheses":hypotheses,"cost_headline":overall_cost,"placement_headline":overall_placement,"sensitivity_headline":sensitivity["headline"],"scientific_outcome":{"cost":"CONFIRMED" if hypotheses["cost_strict_mape_and_wape_all_topologies"] else "NOT_CONFIRMED","placement":"CONFIRMED" if hypotheses["placement_agreement_weakly_improved"] and hypotheses["placement_mean_regret_weakly_improved"] else "NOT_CONFIRMED"},"training_performed":False,"checkpoint_loaded":False,"prediction_recomputed":False,"teacher_recomputed":False,"gpu_used":False,"proved":"deterministic bin-mean conversion of the frozen Phase49/50 six-model histograms to Phase51 physical communication cost and communication-only topology decisions","not_proved":"new blind generalization, exact per-message cost within bins, end-to-end latency, compute/memory/availability/queueing/congestion/overlap or a full scheduler"};write_json(output/"summary.json",summary)
    cost_lines="; ".join(f"{r['topology_level']} WAPE ratio={float(r['cost_wape_ratio']):.4f}, MAPE ratio={float(r['cost_mape_ratio']):.4f}" for r in overall_cost);(output/"README.md").write_text(f"# Phase52：纯PD物理通信代价与placement验证\n\n状态：`PASS`。固定Phase49预测、Phase50 Hfull和Phase51物理曲线，完成1800个画像×模型单元、两种方法和L1/L2/L3的确定性bin-mean卷积。{cost_lines}。placement agreement：H0={float(overall_placement['h0']['agreement_rate']):.4f}，H0+DNN={float(overall_placement['h0_plus_dnn_residual']['agreement_rate']):.4f}；mean regret：H0={float(overall_placement['h0']['mean_teacher_regret']):.6f}，H0+DNN={float(overall_placement['h0_plus_dnn_residual']['mean_teacher_regret']):.6f}。本阶段不训练、不重算预测/teacher、不使用GPU；结论仅限communication-only。\n",encoding="utf-8");(output/"logs").mkdir();(output/"logs/runtime.log").write_text(f"completed={utc_now()} workflow_commit={expected}\nstatus=PASS costs={len(costs)} decisions={len(decisions)}\ncost_hypothesis={hypotheses['cost_strict_mape_and_wape_all_topologies']} placement_agreement={hypotheses['placement_agreement_weakly_improved']} placement_regret={hypotheses['placement_mean_regret_weakly_improved']}\ngpu=false training=false checkpoint=false prediction_recompute=false teacher_recompute=false\n",encoding="utf-8");(output/"DONE").write_text("PASS\n",encoding="utf-8");refresh_manifest(output);tree=validate_result_tree(output)
    if not tree["ok"]:raise RuntimeError(tree)
    return summary
def _teacher_invariant(costs:list[dict])->bool:
    seen={}
    for row in costs:
        key=(row["profile_id"],row["model"],row["topology_level"]);value=(float(row["teacher_cost_us_per_1000"]),float(row["teacher_cost_lower_us_per_1000"]),float(row["teacher_cost_monotone_us_per_1000"]))
        if key in seen and seen[key]!=value:return False
        seen[key]=value
    return len(seen)==5400
def _sensitivity(curves:list[dict],metrics:list[dict],decisions:list[dict],clamps:dict,quality:dict)->dict:
    inversions=[]
    for curve in curves:
        values=[float(k["official_latency_us"]) for k in curve["knots"]];drops=[(values[i-1]-values[i])/values[i-1] for i in range(1,len(values)) if values[i]<values[i-1]];inversions.append({"curve_id":curve["curve_id"],"inversion_count":len(drops),"maximum_relative_drop":max(drops,default=0.0)})
    overall={r["method"]:r for r in metrics if r["slice_type"]=="overall"};headline={method:{"predicted_interval_robust_fraction":row["predicted_interval_robust_fraction"],"teacher_interval_robust_fraction":row["teacher_interval_robust_fraction"],"monotone_selected_stability":row["monotone_selected_stability"],"monotone_oracle_stability":row["monotone_oracle_stability"]} for method,row in overall.items()};headline["clamps"]=clamps
    return {"schema_version":"phase52-curve-and-placement-sensitivity-v1","headline":headline,"curve_inversions":inversions,"phase51_final_runtime_variance_measurements":len(quality.get("final_runtime_variance",[])),"phase51_placement_variance_knots":int(quality.get("placement_knots_above_threshold",0)),"placement_decisions":len(decisions),"official_result_uses_unsmoothed_curves":True,"monotone_curves_diagnostic_only":True}
def main()->None:
    p=argparse.ArgumentParser();p.add_argument("--expected-workflow-commit",required=True);p.add_argument("--output-dir",type=Path,default=repo_root()/"experiment-results/phase52_pd_physical_cost_placement_validation");a=p.parse_args();print(json.dumps(run(a.expected_workflow_commit,a.output_dir.resolve()),ensure_ascii=False,indent=2))
if __name__=="__main__":main()
