#!/usr/bin/env python3
"""Independent Phase52 compact-result verifier."""
from __future__ import annotations
import argparse,json,math,sys
from pathlib import Path
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE.parent));sys.path.insert(0,str(HERE))
from common import load_json,repo_root,verify_result_manifest  # noqa:E402
from analysis import read_csv  # noqa:E402

def verify(output:Path)->dict:
    expected=load_json(HERE/"expected_outputs.json");missing=[name for name in expected["required"] if not (output/name).is_file()]
    if missing:raise RuntimeError({"missing":missing})
    manifest=verify_result_manifest(output);workflow=load_json(HERE/"experiment.json");result_contract=load_json(output/"contracts/experiment.json");summary=load_json(output/"summary.json");freeze=load_json(output/"audit/input_freeze.json");interpolation=load_json(output/"audit/interpolation.json");sensitivity=load_json(output/"audit/sensitivity.json");environment=load_json(output/"audit/environment.json");costs=read_csv(output/"analysis/unit_topology_costs.csv.gz");cost_metrics=read_csv(output/"analysis/cost_metrics.csv");cost_comparison=read_csv(output/"analysis/cost_method_comparison.csv");rankings=read_csv(output/"analysis/placement_rankings.csv.gz");decisions=read_csv(output/"analysis/placement_decisions.csv.gz");placement_metrics=read_csv(output/"analysis/placement_metrics.csv");placement_comparison=read_csv(output/"analysis/placement_method_comparison.csv");counts=workflow["expected_counts"]
    cost_keys={(r["profile_id"],r["model"],r["method"],r["topology_level"]) for r in costs};decision_keys={(r["profile_id"],r["model"],r["method"]) for r in decisions};overall_cost=[r for r in cost_comparison if r["slice_type"]=="overall"];overall_place=next(r for r in placement_comparison if r["slice_type"]=="overall");hypotheses={"cost_strict_mape_and_wape_all_topologies":len(overall_cost)==3 and all(r["strict_mape_and_wape_improvement"]=="True" for r in overall_cost),"placement_agreement_weakly_improved":overall_place["agreement_weakly_improved"]=="True","placement_mean_regret_weakly_improved":overall_place["mean_regret_weakly_improved"]=="True"}
    checks={"manifest":manifest["ok"],"required_exact":set(expected["required"])=={str(p.relative_to(output)) for p in output.rglob("*") if p.is_file()},"status":summary.get("status")=="PASS" and (output/"DONE").read_text().strip()=="PASS","contract_exact":result_contract==workflow,"parent":freeze.get("workflow_parent_result_commit")==workflow["workflow_parent_result_commit"],"pins":all(v.get("ok") is True for v in freeze.get("pinned_inputs",{}).values()),"counts":len(costs)==counts["unit_topology_cost_rows"] and len(rankings)==counts["placement_ranking_rows"] and len(decisions)==counts["placement_decision_rows"] and len(cost_metrics)==counts["cost_metric_rows"] and len(cost_comparison)==counts["cost_comparison_rows"] and len(placement_metrics)==counts["placement_metric_rows"] and len(placement_comparison)==counts["placement_comparison_rows"],"cost_keys":len(cost_keys)==10800 and {r["method"] for r in costs}=={"h0","h0_plus_dnn_residual"} and {r["topology_level"] for r in costs}=={"L1","L2","L3"},"decision_keys":len(decision_keys)==3600 and all(r["selected_topology"] in {"L1","L2","L3"} and r["oracle_topology"] in {"L1","L2","L3"} and float(r["teacher_regret"])>=-1e-12 and r["ranking_scope"]=="communication_only_fixed_p1_d1_configuration" for r in decisions),"finite_costs":all(math.isfinite(float(r[name])) and float(r[name])>=0 for r in costs for name in ("predicted_cost_us_per_1000","teacher_cost_us_per_1000","predicted_cost_lower_us_per_1000","teacher_cost_lower_us_per_1000")),"hypotheses":summary.get("hypotheses")==hypotheses,"interpolation":interpolation.get("schema_version")=="phase52-interpolation-audit-v1" and len(interpolation.get("roles",{}))==216,"sensitivity":sensitivity.get("official_result_uses_unsmoothed_curves") is True and sensitivity.get("monotone_curves_diagnostic_only") is True and len(sensitivity.get("curve_inversions",[]))==18,"scope":summary.get("training_performed") is False and summary.get("checkpoint_loaded") is False and summary.get("prediction_recomputed") is False and summary.get("teacher_recomputed") is False and summary.get("gpu_used") is False and environment.get("gpu_used") is False and environment.get("network_used") is False,"no_raw_or_model":not list(output.rglob("*.jsonl")) and not list(output.rglob("*.safetensors"))}
    if not all(checks.values()):raise RuntimeError({"checks":checks,"manifest":manifest})
    return {"status":"PASS","checks":checks,"workflow_commit":summary["workflow_commit"],"cost_rows":len(costs),"decisions":len(decisions),"scientific_outcome":summary["scientific_outcome"],"manifest_files":manifest["manifest"]["checked_files"]}
def main()->None:
    p=argparse.ArgumentParser();p.add_argument("--output-dir",type=Path,default=repo_root()/"experiment-results/phase52_pd_physical_cost_placement_validation");a=p.parse_args();print(json.dumps(verify(a.output_dir.resolve()),ensure_ascii=False,indent=2))
if __name__=="__main__":main()
