#!/usr/bin/env python3
"""Aggregate complete Phase70 raw and evaluate the frozen R69 formula."""
from __future__ import annotations
import argparse,csv,json,sys
from pathlib import Path
from typing import Any
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE.parent));sys.path.insert(0,str(HERE))
from common import environment_record,load_json,refresh_manifest,repo_root,require_clean_before_run,require_expected_head,utc_now,validate_result_tree,verify_pinned_inputs,write_json  # noqa:E402
from contracts import file_sha,frozen_model,frozen_r67_model,layouts,reserved_grid,r61_baseline,r65_baseline,validate_blind_contract,validate_plan  # noqa:E402
from measurement import build_analysis,validate_raw  # noqa:E402
def write_csv(path:Path,rows:list[dict[str,Any]])->None:
 if not rows:raise RuntimeError(f"empty CSV: {path}")
 path.parent.mkdir(parents=True,exist_ok=True);fields=list(dict.fromkeys(key for row in rows for key in row))
 with path.open("w",encoding="utf-8",newline="") as stream:writer=csv.DictWriter(stream,fieldnames=fields,lineterminator="\n");writer.writeheader();writer.writerows(rows)
def result_status(runtime:bool,placement:bool)->str:return "PASS_WITH_RUNTIME_AND_PLACEMENT_VARIANCE" if runtime and placement else "PASS_WITH_RUNTIME_VARIANCE" if runtime else "PASS_WITH_PLACEMENT_VARIANCE" if placement else "PASS"
def run(expected:str,plan_path:Path,raw_dir:Path,preflight_path:Path,output:Path)->dict[str,Any]:
 head=require_expected_head(expected);require_clean_before_run();spec=load_json(HERE/"experiment.json");pins=verify_pinned_inputs(spec)
 if output.exists():raise RuntimeError(f"refuse overwrite: {output}")
 plan_path=plan_path.expanduser().resolve();raw_dir=raw_dir.expanduser().resolve();preflight_path=preflight_path.expanduser().resolve();plan=load_json(plan_path);plan_audit=validate_plan(plan)
 if plan["workflow_commit"]!=head:raise RuntimeError({"plan":plan["workflow_commit"],"HEAD":head})
 preflight=load_json(preflight_path);groups=[preflight.get(key,{}) for key in ("environment_checks","module_checks","runtime_checks")]
 if preflight.get("status")!="PASS" or preflight.get("workflow_commit")!=head or preflight.get("plan_audit",{}).get("plan_sha256")!=plan["plan_sha256"] or preflight.get("plan_file_sha256")!=file_sha(plan_path) or Path(preflight.get("raw_dir","")).resolve()!=raw_dir or preflight.get("environment",{}).get("declared_container_image")!=spec["container_contract"]["image"] or preflight.get("frozen_formula",{}).get("file_sha256")!=spec["frozen_correction_contract"]["sha256"] or preflight.get("frozen_formula",{}).get("phase70_targets_read") is not False or any(not group or not all(group.values()) for group in groups):raise RuntimeError("Phase70 preflight/plan/raw/formula binding failed")
 raw=validate_raw(plan,raw_dir,require_complete=True);analysis=build_analysis(plan,raw);runtime=bool(raw["final_runtime_variance"]);placement=any(row["above_threshold"] for row in analysis["spreads"]);status=result_status(runtime,placement);blind_audit=validate_blind_contract(spec);output.mkdir(parents=True)
 write_json(output/"contracts/experiment.json",spec);write_json(output/"contracts/topology_plan.json",plan);write_json(output/"contracts/selected_model_transfer_layouts.json",{"schema_version":"phase70-selected-layouts-v1","layouts":layouts(spec)});write_json(output/"contracts/reserved_blind_grid.json",reserved_grid());write_json(output/"contracts/frozen_phase69_high_page_residual.json",frozen_model());write_json(output/"contracts/frozen_phase67_graph_page_correction.json",frozen_r67_model());write_json(output/"contracts/frozen_r65_baseline.json",r65_baseline());write_json(output/"contracts/frozen_r61_baseline.json",r61_baseline())
 write_json(output/"evidence/fresh_blind_points.json",{"schema_version":"phase70-third-fresh-blind-points-v1","workflow_commit":head,"source_development_result_commit":spec["source_development_result_commit"],"source_prior_blind_result_commit":spec["source_prior_blind_result_commit"],"source_physical_curve_result_commit":spec["source_physical_curve_result_commit"],"plan_sha256":plan["plan_sha256"],"points":analysis["points"],"replica_points":analysis["replica_points"]})
 write_csv(output/"analysis/fresh_blind_points.csv",analysis["points"]);write_csv(output/"analysis/fresh_blind_metrics.csv",analysis["metrics"]);write_csv(output/"analysis/replica_points.csv",analysis["replica_points"]);write_csv(output/"analysis/replica_spread.csv",analysis["spreads"])
 write_json(output/"audit/input_freeze.json",{"schema_version":"phase70-input-freeze-v1","workflow_commit":head,"workflow_parent_result_commit":spec["workflow_parent_result_commit"],"source_development_result_commit":spec["source_development_result_commit"],"source_prior_blind_result_commit":spec["source_prior_blind_result_commit"],"source_physical_curve_result_commit":spec["source_physical_curve_result_commit"],"pinned_inputs":pins,"plan_sha256":plan["plan_sha256"],"plan_file_sha256":file_sha(plan_path),"preflight_file_sha256":file_sha(preflight_path),"reserved_grid_sha256":blind_audit["grid_sha256"],"frozen_model_file_sha256":spec["frozen_correction_contract"]["sha256"],"frozen_anchor_model_file_sha256":spec["frozen_correction_contract"]["anchor_r67_sha256"],"prior_endpoint_overlap_count":plan["placement_summary"]["prior_endpoint_overlap_count"],"new_host_signatures_by_topology":plan["placement_summary"]["new_host_signatures_by_topology"],"training_performed":False,"recalibration_performed":False,"threshold_tuning_performed":False,"phase70_labels_used_for_fitting":False})
 write_json(output/"audit/external_raw_manifest.json",{"schema_version":"phase70-external-raw-manifest-v1","raw_committed_to_git":False,"raw_root_recorded":str(raw_dir),"counts":raw["counts"],"files":raw["files"]});write_json(output/"audit/measurement_quality.json",{"schema_version":"phase70-measurement-quality-v1","repeat_policy":spec["measurement_contract"],"measurements":raw["measurements"],"final_runtime_variance":raw["final_runtime_variance"],"placement_spread_threshold":spec["measurement_contract"]["cross_replica_relative_spread_diagnostic_threshold"],"placement_points_above_threshold":sum(row["above_threshold"] for row in analysis["spreads"])})
 safe=("rank","role","hostname","expected_host","physical_gpu","visible_gpu","gpu_name","gpu_uuid","ib_device","mooncake_protocol","with_nvidia_peermem","torch","cuda","python");runtime_endpoints=[]
 for measurement in plan["measurements"]:
  first_repeat=next(iter(raw["records"][measurement["measurement_id"]].values()));first=first_repeat[0];runtime_endpoints.append({"measurement_id":measurement["measurement_id"],"world_size":measurement["world_size"],"endpoints":[{key:endpoint.get(key) for key in safe} for endpoint in first["runtime_endpoints"]]})
 write_json(output/"audit/environment.json",{"aggregation":environment_record(),"gpu_measurement_preflight":preflight,"gpu_measurement_runtime_endpoints":runtime_endpoints})
 overall=next(row for row in analysis["metrics"] if row["slice_type"]=="overall");summary={"schema_version":"phase70-pd-high-page-residual-fresh-blind-result-v1","status":status,"scientific_outcome":analysis["decision"]["scientific_outcome"],"workflow_commit":head,"workflow_parent_result_commit":spec["workflow_parent_result_commit"],"source_development_result_commit":spec["source_development_result_commit"],"source_prior_blind_result_commit":spec["source_prior_blind_result_commit"],"source_physical_curve_result_commit":spec["source_physical_curve_result_commit"],"completed_at_utc":utc_now(),"counts":{"models":2,"configurations":4,"topology_levels":3,"placement_replicas":2,"measurement_shards":48,"official_points":len(analysis["points"]),"replica_points":len(analysis["replica_points"]),"maximum_simultaneous_flows":4,"maximum_world_size_per_shard":5,"scheduler_reservation_mode":plan["placement_summary"]["scheduler_reservation_mode"],"preferred_scheduler_reserved_nodes":4,"maximum_scheduler_reserved_nodes":4,"maximum_active_measurement_nodes_per_shard":2,"global_peak_simultaneous_gpu_processes":5,"maximum_concurrent_measurement_shards":1,"prior_endpoint_overlap_count":0,"raw_files":raw["counts"]["files"],"raw_records":raw["counts"]["records"]},"metrics":{"max_edge_overall_wape":overall["max_edge_wape"],"r61_graph_overall_wape":overall["r61_graph_wape"],"phase65_overall_wape":overall["phase65_wape"],"phase67_overall_wape":overall["phase67_wape"],"phase69_overall_wape":overall["phase69_wape"],"phase69_overall_signed_bias":overall["phase69_signed_bias"]},"decision":analysis["decision"],"runtime_variance_measurements":len(raw["final_runtime_variance"]),"placement_variance_points":sum(row["above_threshold"] for row in analysis["spreads"]),"transport":"SGLang production MooncakeTransferEngine.batch_transfer_sync over RDMA/dma-buf","training_performed":False,"recalibration_performed":False,"threshold_tuning_performed":False,"model_weights_loaded":False,"inference_performed":False,"histograms_recomputed":False,"phase70_labels_used_for_fitting":False,"proved":"third fresh-blind physical evaluation of frozen R69 high-page residual correction on new pages and placements for two models/four graphs/L1-L3","not_proved":"unseen models, larger/different graphs, end-to-end serving, routing-aware histogram prediction, compute, memory, queueing, unrelated-job congestion, online arrivals or scheduler placement selection"};write_json(output/"summary.json",summary)
 (output/"README.md").write_text(f"# Phase70：PD高page残差第三次fresh-blind验证\n\n执行状态：{status}；科学结论：{summary['scientific_outcome']}。48个GPU shard、240个official point；max-edge WAPE={overall['max_edge_wape']:.6f}，R61 WAPE={overall['r61_graph_wape']:.6f}，R65 WAPE={overall['phase65_wape']:.6f}，冻结R67 WAPE={overall['phase67_wape']:.6f}，冻结R69 WAPE={overall['phase69_wape']:.6f}。所有endpoint tuple同时避开Phase64/66/68；raw仅在Git外，无训练、重校准或阈值修改。\n",encoding="utf-8");(output/"logs").mkdir();(output/"logs/runtime.log").write_text(f"completed={utc_now()} workflow_commit={head}\nstatus={status} scientific_outcome={summary['scientific_outcome']}\nmeasurements=48 points=240 replica_points=480 raw_files={raw['counts']['files']} raw_records={raw['counts']['records']} reservation_mode={plan['placement_summary']['scheduler_reservation_mode']} max_reserved_nodes=4 max_active_nodes=2 peak_gpu_processes=5 concurrent_shards=1 prior_endpoint_overlap=0\nmax_edge_wape={overall['max_edge_wape']} r61_wape={overall['r61_graph_wape']} phase65_wape={overall['phase65_wape']} phase67_wape={overall['phase67_wape']} phase69_wape={overall['phase69_wape']} phase69_bias={overall['phase69_signed_bias']}\ntraining=false recalibration=false threshold_tuning=false phase70_labels_used_for_fitting=false raw_committed=false\n",encoding="utf-8");(output/"DONE").write_text(status+"\n",encoding="utf-8");refresh_manifest(output);tree=validate_result_tree(output)
 if not tree["ok"]:raise RuntimeError(tree)
 return summary
def main()->None:
 parser=argparse.ArgumentParser();parser.add_argument("--expected-workflow-commit",required=True);parser.add_argument("--topology-plan",type=Path,required=True);parser.add_argument("--raw-dir",type=Path,required=True);parser.add_argument("--preflight-audit",type=Path,required=True);parser.add_argument("--output-dir",type=Path,default=repo_root()/"experiment-results/phase70_pd_high_page_residual_fresh_blind");args=parser.parse_args();print(json.dumps(run(args.expected_workflow_commit,args.topology_plan,args.raw_dir,args.preflight_audit,args.output_dir.resolve()),ensure_ascii=False,indent=2))
if __name__=="__main__":main()
