#!/usr/bin/env python3
from __future__ import annotations
import argparse, gzip, json, sys
from pathlib import Path
HERE=Path(__file__).resolve().parent; P57=HERE.parent/"phase57_pd_iterative_histogram_optimization"; sys.path.insert(0,str(P57)); sys.path.insert(0,str(HERE)); sys.path.insert(0,str(HERE.parent))
from common import load_json, repo_root, run_git, verify_result_manifest  # noqa: E402
from model_loader import read_csv, read_csv_gz  # noqa: E402
def verify(output: Path) -> dict:
    expected=load_json(HERE/"expected_outputs.json"); manifest=verify_result_manifest(output); summary=load_json(output/"summary.json"); required=set(expected["required"]); actual={str(p.relative_to(output)) for p in output.rglob("*") if p.is_file()}; trace=read_csv(output/"analysis/round_trace.csv"); candidates=read_csv(output/"analysis/oof_candidate_metrics.csv"); predictions=read_csv_gz(output/"predictions/development_validation_predictions.csv.gz"); checkpoint=json.load(gzip.open(output/"checkpoints/pd_shape_aware_iterative_refinement.json.gz","rt",encoding="utf-8")); search=load_json(output/"audit/search.json"); env=load_json(output/"audit/environment.json"); gates=summary["gates"]; n=len(candidates); head=run_git(["rev-parse","HEAD"]); parents=run_git(["rev-list","--parents","-n","1","HEAD"]).split(); workflow_commit=summary.get("workflow_commit"); head_or_parent=workflow_commit==head or (len(parents)==2 and workflow_commit==parents[1])
    checks={"manifest":manifest["ok"],"required_outputs":required.issubset(actual),"status":summary.get("status")=="PASS","done":(output/"DONE").read_text(encoding="utf-8").strip()=="PASS","workflow_head_exact_or_result_child":head_or_parent and checkpoint.get("workflow_commit")==workflow_commit,"result_parent_unique":len(parents)==2,"candidate_budget":0<n<=36 and n==len(trace) and n%12==0,"round_count":1<=int(search["rounds_completed"])<=3 and int(search["candidate_budget"])==n,"prediction_rows_2880":len(predictions)==2880,"prediction_methods":{r["method"] for r in predictions}=={"h0","h0_plus_dnn_shape_aware"},"profiles_240":len({r["profile_id"] for r in predictions})==240,"models_6":len({r["model"] for r in predictions})==6,"counts_exact":summary["counts"]["profiles"]==1200 and summary["counts"]["train_profiles"]==960 and summary["counts"]["validation_profiles"]==240 and summary["counts"]["models"]==6 and summary["counts"]["segments"]==3 and summary["counts"]["example_rows"]==7200 and summary["counts"]["train_rows"]==5760 and summary["counts"]["validation_rows"]==1440 and summary["counts"]["candidates"]==n and summary["counts"]["complete_request_rows_in_git"]==0,"one_selected":sum(1 for r in candidates if r.get("selected")=="True")==1,"validation_after_freeze":search["validation_opened_once_after_freeze"] is True,"no_blind":checkpoint["phase50_blind_accessed"] is False and search["phase50_blind_accessed"] is False,"no_complete_requests":checkpoint["complete_requests_accessed"] is False and search["complete_requests_accessed"] is False,"gate_consistency":gates["target_met"]==all([gates["development_overall"],gates["development_all_models"],gates["development_all_segments"]]),"next_permission":gates["next_phase_permitted"]==gates["target_met"],"cpu_only":env["gpu_used"] is False and env["network_used"] is False}
    if not all(checks.values()): raise RuntimeError(checks)
    return {"status":"PASS","checks":checks,"manifest_files":manifest["manifest"]["checked_files"],"scientific_outcome":summary["scientific_outcome"],"target_met":gates["target_met"],"candidate_count":n}
def main() -> None:
    parser=argparse.ArgumentParser(); parser.add_argument("--output-dir",type=Path,default=repo_root()/"experiment-results/phase58_pd_shape_aware_iterative_refinement"); args=parser.parse_args(); print(json.dumps(verify(args.output_dir.resolve()),ensure_ascii=False,indent=2))
if __name__ == "__main__": main()
