#!/usr/bin/env python3
"""Aggregate complete Phase64 raw and evaluate the frozen graph formula."""
from __future__ import annotations
import argparse,csv,json,sys
from pathlib import Path
from typing import Any
HERE=Path(__file__).resolve().parent;sys.path.insert(0,str(HERE.parent));sys.path.insert(0,str(HERE))
from common import environment_record,load_json,refresh_manifest,repo_root,require_clean_before_run,require_expected_head,utc_now,validate_result_tree,verify_pinned_inputs,write_json  # noqa:E402
from contracts import file_sha,graph_grid,layouts,validate_graph_contract,validate_plan  # noqa:E402
from measurement import build_analysis,validate_raw  # noqa:E402
def write_csv(path:Path,rows:list[dict[str,Any]])->None:
 if not rows:raise RuntimeError(f"empty CSV: {path}")
 path.parent.mkdir(parents=True,exist_ok=True);fields=list(dict.fromkeys(k for row in rows for k in row))
 with path.open("w",encoding="utf-8",newline="") as f:w=csv.DictWriter(f,fieldnames=fields,lineterminator="\n");w.writeheader();w.writerows(rows)
def result_status(runtime:bool,placement:bool)->str:
 return "PASS_WITH_RUNTIME_AND_PLACEMENT_VARIANCE" if runtime and placement else "PASS_WITH_RUNTIME_VARIANCE" if runtime else "PASS_WITH_PLACEMENT_VARIANCE" if placement else "PASS"
def run(expected:str,plan_path:Path,raw_dir:Path,preflight_path:Path,output:Path)->dict[str,Any]:
 head=require_expected_head(expected);require_clean_before_run();spec=load_json(HERE/"experiment.json");pins=verify_pinned_inputs(spec)
 if output.exists():raise RuntimeError(f"refuse overwrite: {output}")
 plan_path=plan_path.expanduser().resolve();raw_dir=raw_dir.expanduser().resolve();preflight_path=preflight_path.expanduser().resolve();plan=load_json(plan_path);plan_audit=validate_plan(plan)
 if plan["workflow_commit"]!=head:raise RuntimeError({"plan":plan["workflow_commit"],"HEAD":head})
 preflight=load_json(preflight_path);groups=[preflight.get(k,{}) for k in ("environment_checks","module_checks","runtime_checks")]
 if preflight.get("status")!="PASS" or preflight.get("workflow_commit")!=head or preflight.get("plan_audit",{}).get("plan_sha256")!=plan["plan_sha256"] or preflight.get("plan_file_sha256")!=file_sha(plan_path) or Path(preflight.get("raw_dir","")).resolve()!=raw_dir or preflight.get("environment",{}).get("declared_container_image")!=spec["container_contract"]["image"] or preflight.get("frozen_formula",{}).get("file_sha256")!=spec["graph_formula_contract"]["sha256"] or any(not g or not all(g.values()) for g in groups):raise RuntimeError("Phase64 preflight/plan/raw/formula binding failed")
 raw=validate_raw(plan,raw_dir,require_complete=True);analysis=build_analysis(plan,raw);runtime=bool(raw["final_runtime_variance"]);placement=any(r["above_threshold"] for r in analysis["spreads"]);status=result_status(runtime,placement);grid_audit=validate_graph_contract(spec);output.mkdir(parents=True)
 write_json(output/"contracts/experiment.json",spec);write_json(output/"contracts/topology_plan.json",plan);write_json(output/"contracts/selected_model_transfer_layouts.json",{"schema_version":"phase64-selected-layouts-v1","layouts":layouts(spec)});write_json(output/"contracts/graph_payload_grid.json",graph_grid());model=load_json(repo_root()/spec["graph_formula_contract"]["source"]);write_json(output/"contracts/frozen_contention_correction.json",model)
 write_json(output/"evidence/multiflow_graph_points.json",{"schema_version":"phase64-multiflow-graph-points-v1","workflow_commit":head,"source_correction_result_commit":spec["source_correction_result_commit"],"source_six_model_validation_result_commit":spec["source_six_model_validation_result_commit"],"plan_sha256":plan["plan_sha256"],"points":analysis["points"],"replica_points":analysis["replica_points"]})
 write_csv(output/"analysis/multiflow_graph_points.csv",analysis["points"]);write_csv(output/"analysis/multiflow_graph_metrics.csv",analysis["metrics"]);write_csv(output/"analysis/replica_points.csv",analysis["replica_points"]);write_csv(output/"analysis/replica_spread.csv",analysis["spreads"])
 write_json(output/"audit/input_freeze.json",{"schema_version":"phase64-input-freeze-v1","workflow_commit":head,"workflow_parent_result_commit":spec["workflow_parent_result_commit"],"source_correction_result_commit":spec["source_correction_result_commit"],"source_six_model_validation_result_commit":spec["source_six_model_validation_result_commit"],"pinned_inputs":pins,"plan_sha256":plan["plan_sha256"],"plan_file_sha256":file_sha(plan_path),"preflight_file_sha256":file_sha(preflight_path),"graph_grid_sha256":grid_audit["grid_sha256"],"frozen_model_file_sha256":spec["graph_formula_contract"]["sha256"],"training_performed":False,"recalibration_performed":False,"threshold_tuning_performed":False,"phase64_labels_used_for_fitting":False})
 write_json(output/"audit/external_raw_manifest.json",{"schema_version":"phase64-external-raw-manifest-v1","raw_committed_to_git":False,"raw_root_recorded":str(raw_dir),"counts":raw["counts"],"files":raw["files"]});write_json(output/"audit/measurement_quality.json",{"schema_version":"phase64-measurement-quality-v1","repeat_policy":spec["measurement_contract"],"measurements":raw["measurements"],"final_runtime_variance":raw["final_runtime_variance"],"placement_spread_threshold":spec["measurement_contract"]["cross_replica_relative_spread_diagnostic_threshold"],"placement_points_above_threshold":sum(r["above_threshold"] for r in analysis["spreads"])})
 safe=("rank","role","hostname","expected_host","physical_gpu","visible_gpu","gpu_name","gpu_uuid","ib_device","mooncake_protocol","with_nvidia_peermem","torch","cuda","python");runtime_endpoints=[]
 for m in plan["measurements"]:
  first_repeat=next(iter(raw["records"][m["measurement_id"]].values()));first=first_repeat[0];runtime_endpoints.append({"measurement_id":m["measurement_id"],"world_size":m["world_size"],"endpoints":[{k:e.get(k) for k in safe} for e in first["runtime_endpoints"]]})
 write_json(output/"audit/environment.json",{"aggregation":environment_record(),"gpu_measurement_preflight":preflight,"gpu_measurement_runtime_endpoints":runtime_endpoints})
 overall=next(r for r in analysis["metrics"] if r["slice_type"]=="overall");summary={"schema_version":"phase64-pd-multiflow-graph-zero-shot-result-v1","status":status,"scientific_outcome":analysis["decision"]["scientific_outcome"],"workflow_commit":head,"workflow_parent_result_commit":spec["workflow_parent_result_commit"],"source_correction_result_commit":spec["source_correction_result_commit"],"completed_at_utc":utc_now(),"counts":{"models":2,"configurations":4,"topology_levels":3,"placement_replicas":2,"measurement_shards":48,"official_points":len(analysis["points"]),"replica_points":len(analysis["replica_points"]),"maximum_simultaneous_flows":4,"maximum_world_size_per_shard":5,"maximum_simultaneous_nodes_per_shard":2,"global_peak_simultaneous_nodes":2,"global_peak_simultaneous_gpu_processes":5,"maximum_concurrent_measurement_shards":1,"raw_files":raw["counts"]["files"],"raw_records":raw["counts"]["records"]},"metrics":{"max_edge_overall_wape":overall["max_edge_wape"],"graph_formula_overall_wape":overall["graph_wape"],"graph_formula_overall_signed_bias":overall["graph_signed_bias"]},"decision":analysis["decision"],"runtime_variance_measurements":len(raw["final_runtime_variance"]),"placement_variance_points":sum(r["above_threshold"] for r in analysis["spreads"]),"transport":"SGLang production MooncakeTransferEngine.batch_transfer_sync over RDMA/dma-buf","training_performed":False,"recalibration_performed":False,"model_weights_loaded":False,"inference_performed":False,"histograms_recomputed":False,"phase64_labels_used_for_fitting":False,"proved":"zero-shot physical evaluation of a frozen graph-composition formula for at most four simultaneous edges in P1D4/P4D1/P2D2 matching/all-to-all","not_proved":"larger dense graphs, end-to-end serving, routing-aware histogram prediction, compute, memory, queueing, unrelated-job congestion, online arrivals or scheduler placement selection"};write_json(output/"summary.json",summary)
 (output/"README.md").write_text(f"# Phase64：PD多流通信图零样本验证\n\n执行状态：{status}；科学结论：{summary['scientific_outcome']}。48个GPU shard、240个official point；max-edge WAPE={overall['max_edge_wape']:.6f}，冻结图公式 WAPE={overall['graph_wape']:.6f}。无训练、无重校准、无模型权重，raw仅在Git外。\n",encoding="utf-8");(output/"logs").mkdir();(output/"logs/runtime.log").write_text(f"completed={utc_now()} workflow_commit={head}\nstatus={status} scientific_outcome={summary['scientific_outcome']}\nmeasurements=48 points=240 replica_points=480 raw_files={raw['counts']['files']} raw_records={raw['counts']['records']} peak_nodes=2 peak_gpu_processes=5 concurrent_shards=1\nmax_edge_wape={overall['max_edge_wape']} graph_wape={overall['graph_wape']} graph_bias={overall['graph_signed_bias']}\ntraining=false recalibration=false phase64_labels_used_for_fitting=false raw_committed=false\n",encoding="utf-8");(output/"DONE").write_text(status+"\n",encoding="utf-8");refresh_manifest(output);tree=validate_result_tree(output)
 if not tree["ok"]:raise RuntimeError(tree)
 return summary
def main()->None:
 p=argparse.ArgumentParser();p.add_argument("--expected-workflow-commit",required=True);p.add_argument("--topology-plan",type=Path,required=True);p.add_argument("--raw-dir",type=Path,required=True);p.add_argument("--preflight-audit",type=Path,required=True);p.add_argument("--output-dir",type=Path,default=repo_root()/"experiment-results/phase64_pd_multiflow_graph_zero_shot");a=p.parse_args();print(json.dumps(run(a.expected_workflow_commit,a.topology_plan,a.raw_dir,a.preflight_audit,a.output_dir.resolve()),ensure_ascii=False,indent=2))
if __name__=="__main__":main()
